Derived MaxEncodedLen
AcalaNetwork/Acala pull request #1036
Opened 2021-05-21 18:22 UTC by brettkolodny

2021-05-21 18:27 UTC, brettkolodny commented
There are already two types for `MaxCandidates` and `MaxInvulnerables` that are tied to the two storage items that need to be migrated to `BoundedVec` but those traits are used for benchmarking only.

Should these be left as `Vec` or should two new types be implemented that serve as maximum amount that should ever be possible?

2021-05-22 04:00 UTC, xlc commented
We have make them strictly enforced

2021-05-24 23:10 UTC, xlc requested changes
I think we still want desired_candidates as a soft limit can be increased without runtime upgrade.

2021-05-24 23:10 UTC, xlc commented on modules/collator-selection/src/lib.rs
>  			// we trust origin calls, this is just a for more accurate benchmarking
this comment can go

2021-05-25 22:32 UTC, xlc approved these changes

2021-05-26 22:11 UTC, merged