Take revenue
AcalaNetwork/Acala pull request #1228
Opened 2021-07-19 04:28 UTC by zjb0807

Closes: #1115

2021-07-19 05:12 UTC, shaunxw requested changes

2021-07-19 05:12 UTC, shaunxw commented on runtime/karura/src/lib.rs
> +		if let MultiAsset::ConcreteFungible { amount, .. } = revenue {
Not all concrete fungible revenue is in KSM, need to check the the location.

2021-07-19 05:12 UTC, shaunxw commented on runtime/mandala/src/lib.rs
> +		if let MultiAsset::ConcreteFungible { amount, .. } = revenue {
Same here.

2021-07-19 05:12 UTC, shaunxw commented on runtime/mandala/src/lib.rs
> +			let _ = Tokens::deposit(AUSD, &TreasuryAccount::get(), amount);
```suggestion
			let _ = Tokens::deposit(DOT, &TreasuryAccount::get(), amount);
```

2021-07-19 05:12 UTC, shaunxw commented on runtime/karura/src/lib.rs
> +impl TakeRevenue for DealWithFees {
I would prefer not to reuse the `DealWithFees`. We should make each struct type concern their own business. Declare a new struct before `XcmConfig` and name it `ToTreasury`.

2021-07-19 06:45 UTC, shaunxw commented on runtime/karura/src/lib.rs
> +			if CurrencyIdConvert::convert(id).is_some() {
`is_some` check only ensures `id` could be converted to a `CurrencyId` but it doesn't have to be KSM.

To handle it correctly, get the wrapped `currency_id` in result and deposit with it.

2021-07-19 07:49 UTC, shaunxw approved these changes
LGTM now. We need to do end to end test before merging it.

2021-07-20 10:23 UTC, zjb0807 commented
![image](https://user-images.githubusercontent.com/16496415/126307772-63fc8fc7-fc69-4ac7-b91a-788884e00746.png)


```
[
  {
    "phase": {
      "applyExtrinsic": 0
    },
    "event": {
      "index": "0x0000",
      "data": [
        {
          "weight": 185277000,
          "class": "Mandatory",
          "paysFee": "Yes"
        }
      ]
    },
    "topics": []
  },
  {
    "phase": {
      "applyExtrinsic": 1
    },
    "event": {
      "index": "0x1e03",
      "data": [
        1
      ]
    },
    "topics": []
  },
  {
    "phase": {
      "applyExtrinsic": 1
    },
    "event": {
      "index": "0x0003",
      "data": [
        "owxc9EpKLTtSjkRmzSytjmJtBgjVcMdNf5ZwCvR1hDjTGSE"
      ]
    },
    "topics": []
  },
  {
    "phase": {
      "applyExtrinsic": 1
    },
    "event": {
      "index": "0x0b00",
      "data": [
        {
          "token": "KSM"
        },
        "owxc9EpKLTtSjkRmzSytjmJtBgjVcMdNf5ZwCvR1hDjTGSE",
        999952000000
      ]
    },
    "topics": []
  },
  {
    "phase": {
      "applyExtrinsic": 1
    },
    "event": {
      "index": "0x0c02",
      "data": [
        {
          "token": "KSM"
        },
        "owxc9EpKLTtSjkRmzSytjmJtBgjVcMdNf5ZwCvR1hDjTGSE",
        999952000000
      ]
    },
    "topics": []
  },
  {
    "phase": {
      "applyExtrinsic": 1
    },
    "event": {
      "index": "0x0c02",
      "data": [
        {
          "token": "KSM"
        },
        "qmmNufxeWaAVLMER2va1v4w2HbuU683c5gGtuxQG4fKTZSb",
        48000000
      ]
    },
    "topics": []
  },
  {
    "phase": {
      "applyExtrinsic": 1
    },
    "event": {
      "index": "0x3502",
      "data": [
        "0xd0fc0b77005cdc143478c9d30527010bc62d51b8cb1b2c2d37643a3c0d5e14af",
        {
          "complete": 600000000
        }
      ]
    },
    "topics": []
  },
  {
    "phase": {
      "applyExtrinsic": 1
    },
    "event": {
      "index": "0x1e04",
      "data": [
        600000000,
        "0x8ffc8978d9512ac029f7a829ebb1a360066c362c1a7e17bef6212178503b505e"
      ]
    },
    "topics": []
  },
  {
    "phase": {
      "applyExtrinsic": 1
    },
    "event": {
      "index": "0x0000",
      "data": [
        {
          "weight": 0,
          "class": "Mandatory",
          "paysFee": "Yes"
        }
      ]
    },
    "topics": []
  }
]
```

The treasury(`qmmNufxeWaAVLMER2va1v4w2HbuU683c5gGtuxQG4fKTZSb`) take revenue of XCM execution fee `48000000`.

2021-07-20 11:15 UTC, xlc commented
How hard to write some tests for this?

2021-07-20 13:46 UTC, zjb0807 commented
> How hard to write some tests for this?

BTW,  learn about the xcm transaction process.

2021-07-20 23:11 UTC, shaunxw commented
We only need to mock the execution of received XCM from Kusama in integration tests. You may refer to the commented out ones in integration tests. https://github.com/AcalaNetwork/Acala/blob/8c69db09747622d20abae1937adef234755c7cea/runtime/mandala/tests/integration_test.rs#L1654

2021-07-22 03:45 UTC, merged