Homa nominate validators
AcalaNetwork/Acala pull request #2734
Opened 2024-04-08 17:40 UTC by wangjj9219

2024-04-15 17:24 UTC, wangjj9219 commented on modules/homa-validator-list/src/lib.rs
> +			updates: Vec<(u16, Vec<T::RelayChainAccountId>)>,
param`updates` will be checked and converted  to `BoundedVec` type in the function body before insert storage .

2024-04-16 01:43 UTC, xlc commented on modules/homa-validator-list/src/lib.rs
> +			updates: Vec<(u16, Vec<T::RelayChainAccountId>)>,
but it is still better to validate it at the time of construct the parameter so a transaction with too many nominations won't even be able to make into tx pool

2024-04-17 00:58 UTC, zjb0807 commented on runtime/karura/src/lib.rs
> +	type WeightInfo = ();
update the WeightInfo

2024-04-17 09:30 UTC, zjb0807 approved these changes

2024-04-18 03:51 UTC, xlc requested changes
should also integrate with nominees-election to allow LDOT holders to elect validators

2024-04-18 03:51 UTC, xlc commented on runtime/acala/src/lib.rs
> +	pub const MaxNominations: u32 = 24;
```suggestion
	pub const MaxNominations: u32 = 16;
```
only 16 for polkadot

2024-04-18 03:51 UTC, xlc commented on runtime/acala/src/lib.rs
> +	type NominationsProvider = HomaValidatorList;
this should be reading from nominees-election pallet

2024-04-18 03:51 UTC, xlc commented on runtime/acala/src/lib.rs
> +	pub MinBondAmount: Balance = 10 * dollar(LDOT);
```suggestion
	pub MinBondAmount: Balance = 1000 * dollar(LDOT);
```

2024-04-18 03:51 UTC, xlc commented on runtime/acala/src/lib.rs
> +	pub ValidatorInsuranceThreshold: Balance = 100_000 * dollar(LDOT);
```suggestion
	pub ValidatorInsuranceThreshold: Balance = 10_000 * dollar(LDOT);
```

2024-04-18 16:19 UTC, wangjj9219 commented
> should also integrate with nominees-election to allow LDOT holders to elect validators

reviewed the designs of `nominee-election` and `homa-validator-list`. They are similar. It seems that `nominee-election` is an earlier design. Later, there was the pallet `homa-validator-list`. Similarly, LDOT holders can give validators Votes to increase its guarantee, and the locked guarantee can be frozen and slashed through governance

Need to confirm, is the design of `homa-validator-list` enough to replace `nominee-election`? Does it need optimization, or some renaming?

2024-04-19 00:37 UTC, xlc commented
This is the intended usage:

Validators what wish to become LDOT validators needs to register themselves using `homa-validator-list` and provide insurance deposit.

Then LDOT holders can nominate LDOT validators using `nominee-election` to pick the top X validators out of all registered validators from `homa-validator-list`

So the deposit for `homa-validator-list` can be low as they have to be top X picked by LDOT holders anyway

2024-04-19 02:28 UTC, wangjj9219 commented
> This is the intended usage:
> 
> Validators what wish to become LDOT validators needs to register themselves using `homa-validator-list` and provide insurance deposit.
> 
> Then LDOT holders can nominate LDOT validators using `nominee-election` to pick the top X validators out of all registered validators from `homa-validator-list`
> 
> So the deposit for `homa-validator-list` can be low as they have to be top X picked by LDOT holders anyway

I understand, `homa-validator-list` serves as a filter, and the pick up logic should be placed in `nominee-election`, and `homa` read nominee from `nominee-election`.

2024-04-26 02:46 UTC, xlc commented on runtime/karura/src/lib.rs
> +	pub ValidatorInsuranceThreshold: Balance = 10_000 * dollar(LKSM);
```suggestion
	pub MinBondAmount: Balance = 100 * dollar(LKSM);
	pub ValidatorInsuranceThreshold: Balance = 1_000 * dollar(LKSM);
```

2024-04-26 02:46 UTC, xlc commented on runtime/acala/src/lib.rs
> +	pub MinCouncilBondThreshold: Balance = dollar(LDOT);
```suggestion
	pub MinNomineesElectionBondThreshold: Balance = 10 * dollar(LDOT);
```

2024-04-26 02:46 UTC, xlc commented on runtime/karura/src/lib.rs
> +	pub MinCouncilBondThreshold: Balance = dollar(LKSM);
```suggestion
	pub MinNomineesElectionBondThreshold: Balance = dollar(LKSM);
```

2024-04-30 04:15 UTC, xlc submitted a review, later dismissed

2024-05-07 23:32 UTC, xlc approved these changes

2024-05-21 08:29 UTC, merged