MultiAddress support Address20
AcalaNetwork/Acala pull request #649
Opened 2020-12-23 01:10 UTC by zjb0807

Closes: #639

2020-12-23 01:37 UTC, xlc requested changes
Should change this
https://github.com/AcalaNetwork/Acala/blob/32adae26059756d87d700eef4426a701f9cc7b70/runtime/mandala/src/lib.rs#L151

to something like

`type Lookup = (Indices, EvmAccounts);`

and in the common runtime, add new `struct EvmIndicesLookup` that use EvmAccount to convert AccountId32 to EvmAddress

2020-12-23 22:01 UTC, xlc commented on modules/evm-accounts/src/lib.rs
> +		let evm_address = T::AddressMapping::get_or_create_evm_address(&a);
Just make it `MultiAddress::Id`

2020-12-24 01:54 UTC, zjb0807 commented on runtime/common/src/lib.rs
> +pub struct EvmIndicesLookup<AccountId, AddressMapping>(PhantomData<(AccountId, AddressMapping)>);
for the comment
```
and in the common runtime, add new struct EvmIndicesLookup that use EvmAccount to convert AccountId32 to EvmAddress
```
I will remove it.

2020-12-26 09:18 UTC, xlc approved these changes

2020-12-26 09:18 UTC, merged