Schedule add reschecule and cancel
AcalaNetwork/Acala pull request #731
Opened 2021-02-08 13:31 UTC by zjb0807

Closes: #701

2021-02-09 00:26 UTC, xlc reviewed
https://github.com/paritytech/substrate/blob/29aca981db5e8bf8b5538e6c7920ded917013ef3/frame/scheduler/src/lib.rs#L703-L712

Should be using those methods for cancel / reschedule

2021-02-09 00:53 UTC, zjb0807 commented on runtime/common/src/precompile/schedule_call.rs
> +				Scheduler::cancel_named(task_id).map_err(|_| ExitError::Other("Cancel schedule failed".into()))?;
Here use the scheduler  to do `cancel/reschedule`

2021-02-09 00:54 UTC, zjb0807 commented on runtime/common/src/precompile/schedule_call.rs
> +				Scheduler::cancel_named(task_id).map_err(|_| ExitError::Other("Cancel schedule failed".into()))?;
EVMSchedulerManager just saves the caller and checks whether it has permission.

2021-02-15 01:05 UTC, zjb0807 commented
It is found that `schedule_named` and `cancel_named` are called with root, and the origin cannot be checked.
Redefine `task_id = id + sender + fee`.
So check origin directly through `task_id`.

2021-02-15 01:52 UTC, xlc requested changes

2021-02-15 01:52 UTC, xlc commented on modules/support/src/lib.rs
> +	fn unreserve_fee(_who: &AccountId, _fee: Balance);
```suggestion
	fn unreserve_fee(who: &AccountId, fee: Balance);
```

2021-02-15 01:52 UTC, xlc commented on runtime/common/src/precompile/schedule_call.rs
> +	let mut be_bytes = [0u8; 96];
you can do `Encode::encode((id, sender, Compact(fee)))`, and `Decode::<(Vec<u8>, H160, Compact<Balance>)>::decode(input)`

Also use compact to save some bytes

2021-02-15 01:52 UTC, xlc commented on runtime/common/src/precompile/schedule_call.rs
> +					ChargeTransactionPayment::unreserve_fee(&from_account, fee.into());
this can only happen if cancel is successful. i.e. we have verified the task id is valid

2021-02-15 21:47 UTC, xlc approved these changes

2021-02-15 21:47 UTC, xlc commented on runtime/common/src/precompile/schedule_call.rs
> +#[derive(Debug, PartialEq, Encode, Decode)]
```suggestion
#[derive(RuntimeDebug, PartialEq, Encode, Decode)]
```

2021-02-15 21:47 UTC, xlc commented on runtime/common/src/precompile/schedule_call.rs
> +	id: Vec<u8>,
```suggestion
	prefix: &'static str,
	id: u32,
```

to avoid another encode

2021-02-17 10:32 UTC, xlc commented on runtime/common/src/precompile/tests.rs
> +		let task_id_len: usize = usize::from_be_bytes(num);
usize is u64 in std and u32 in wasm, so I think should use u32 here

2021-02-17 16:04 UTC, merged